# Generated by Django 4.2.9 on 2024-04-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertmodel',
            name='web_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
