name: Build and deploy
on: [pull_request, staging]


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: python:3.10.4-buster
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: echo hello world
        run: echo 'hello world'



     